<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>dotnet10.csharp14.microservice.restful</RootNamespace>
    <UserSecretsId>ps-api-0001</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\dotnet10-csharp14-microservice-restful.Application\dotnet10-csharp14-microservice-restful.Application.csproj" />
    <ProjectReference Include="..\dotnet10-csharp14-microservice-restful.Infrastructure\dotnet10-csharp14-microservice-restful.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\Contracts\" />
    <Folder Include="Services\Implementations\" />
    <Folder Include="Services\UseCases\" />
  </ItemGroup>

</Project>
